# Generated by Django 5.2.8 on 2025-12-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='modo_oscuro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ocultar_instrucciones',
            field=models.BooleanField(default=False),
        ),
    ]
