# Generated by Django 5.2.8 on 2025-12-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_delete_categoria_clinica'),
        ('usuarios', '0002_estudiante_modo_oscuro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_activos', to='cursos.curso'),
        ),
    ]
