# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_Ficticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('descripcion', models.TextField(verbose_name='Descripción General')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.categoria_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Etapa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('video', models.URLField(verbose_name='Video')),
                ('pregunta', models.TextField(verbose_name='Pregunta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clínico.paciente_ficticio')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_del_Cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Parte del cuerpo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='partes_cuerpo/', verbose_name='Imagen')),
                ('ubicacion_anatomica', models.CharField(max_length=150, verbose_name='Ubicación anatómica')),
                ('funcion', models.TextField(blank=True, verbose_name='Función')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clínico.etapa')),
            ],
        ),
    ]
