"""
Django settings for PaginaKinesiologia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x*e7u_eb3+u5%c)ga#6#8yd8expx^cnujg!=w=z98u=c-7yr&+'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',


    #APLICACIONES PROPIAS

    'applications.usuarios',
    'applications.cursos',
    'applications.clinica',
    'applications.evaluaciones',
    'applications.inscripciones',
    'applications.progreso',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

]

ROOT_URLCONF = 'PaginaKinesiologia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PaginaKinesiologia.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Kinesiología UCN",
    "site_header": "Administración Kinesiología",
    "welcome_sign": "Bienvenid@ al Sistema UCN",
    "site_brand": "UCN Kinesiología",
    "site_logo": "img/logo_UCN.png",
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "copyright": "Universidad Católica del Norte",

"icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "usuarios.Perfil": "fas fa-id-card",
        "usuarios.Estudiante": "fas fa-user-graduate",
        "usuarios.Docente": "fas fa-chalkboard-teacher",
        "cursos.Curso": "fas fa-book-medical",
        "cursos.Aprendizaje_Esperado": "fas fa-bullseye",
        "clinica.Caso": "fas fa-file-medical-alt",
        "clinica.Paciente_Ficticio": "fas fa-procedures",
        "clinica.Etapa": "fas fa-stream",
        "clinica.Tema_Interrogacion": "fas fa-user-md",
        "clinica.Partes_del_Cuerpo": "fas fa-child",
        "evaluaciones.Evaluacion": "fas fa-clipboard-check",
        "evaluaciones.Respuesta_Evaluacion": "fas fa-tasks",
        "evaluaciones.Envio_Docente": "fas fa-paper-plane",
        "inscripciones.Solicitud_Inscripcion": "fas fa-file-signature",
        "progreso.Progreso": "fas fa-chart-line",
    },

    "order_with_respect_to": ["usuarios", "cursos", "inscripciones", "clinica", "evaluaciones", "progreso", "auth"],

    "topmenu_links": [
        {"name": "Volver al Sitio",  "url": "/", "permissions": ["auth.view_user"]},
    ],
    "user_avatar": None,
}



LOGIN_URL = '/'  # al intentar acceder a algo protegido, redirige al login
LOGIN_REDIRECT_URL = '/'  # después de hacer login, va a esta URL
LOGOUT_REDIRECT_URL = '/'

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]


# 🔹 Agrega esta línea:
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = '/media/'
