# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizaje_Esperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Objetivo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.CharField(choices=[('básico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('programa', models.TextField(verbose_name='Programa')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, verbose_name='Estado')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.aprendizaje_esperado')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Categoría Clínica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso')),
            ],
        ),
    ]
