# Generated by Django 5.2.8 on 2025-11-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_remove_paciente_ficticio_categoria'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria_Clinica',
        ),
    ]
