# Generated by Django 5.2.8 on 2025-12-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_delete_categoria_clinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendizaje_esperado',
            options={'verbose_name': 'Aprendizaje Esperado', 'verbose_name_plural': 'Aprendizajes Esperados'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
