# Generated by Django 5.2.8 on 2025-11-22 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_Ficticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.categoria_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('video', models.URLField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente_ficticio')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_del_Cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='partes_cuerpo/')),
                ('ubicacion_anatomica', models.CharField(max_length=150)),
                ('funcion', models.TextField(blank=True)),
                ('correcta', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Interrogacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('pregunta', models.CharField(max_length=500)),
                ('respuesta', models.CharField(max_length=500)),
                ('retroalimentacion', models.TextField()),
                ('correcta', models.BooleanField(default=False)),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.etapa')),
            ],
        ),
    ]
