# Generated by Django 5.2.8 on 2025-11-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_caso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='caso',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
