# Generated by Django 5.2.8 on 2025-11-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_caso_tipo_alter_caso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente_ficticio',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='clinica.caso'),
        ),
    ]
