# Generated by Django 5.2.8 on 2025-11-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_paciente_ficticio_caso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente_ficticio',
            name='categoria',
        ),
    ]
