# Generated by Django 5.2.8 on 2025-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_remove_paciente_ficticio_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema_interrogacion',
            old_name='correcta',
            new_name='es_correcta',
        ),
        migrations.RemoveField(
            model_name='tema_interrogacion',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='tema_interrogacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tema_interrogacion',
            name='retroalimentacion',
        ),
        migrations.AddField(
            model_name='tema_interrogacion',
            name='justificacion_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tema_interrogacion',
            name='pregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tema_interrogacion',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
