# Generated by Django 5.2.8 on 2025-11-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_rename_correcta_tema_interrogacion_es_correcta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes_del_cuerpo',
            name='imagen',
        ),
    ]
