# Generated by Django 5.2.8 on 2025-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_remove_partes_del_cuerpo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes_del_cuerpo',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='partes_del_cuerpo',
            name='ubicacion_anatomica',
        ),
        migrations.AddField(
            model_name='partes_del_cuerpo',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partes_del_cuerpo',
            name='top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partes_del_cuerpo',
            name='nombre',
            field=models.CharField(choices=[('cabeza', 'Cabeza'), ('cuello', 'Cuello'), ('mano_izquierda', 'Mano Izquierda'), ('mano_derecha', 'Mano Derecha'), ('codo_izquierdo', 'Codo Izquierdo'), ('codo_derecho', 'Codo Derecho'), ('hombro_izquierdo', 'Hombro Izquierdo'), ('hombro_derecho', 'Hombro Derecho'), ('espalda', 'Espalda'), ('pecho', 'Pecho'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('muslo_izquierdo', 'Muslo Izquierdo'), ('muslo_derecho', 'Muslo Derecho'), ('rodilla_izquierda', 'Rodilla Izquierda'), ('rodilla_derecha', 'Rodilla Derecha'), ('pie_izquierdo', 'Pie Izquierdo'), ('pie_derecho', 'Pie Derecho')], max_length=150),
        ),
    ]
