# Generated by Django 5.2.8 on 2025-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_paciente_ficticio_docente_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente_ficticio',
            name='docente_asignado',
        ),
    ]
