# Generated by Django 5.2.8 on 2025-11-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_remove_paciente_ficticio_docente_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes_del_cuerpo',
            name='left',
            field=models.IntegerField(default=0, help_text='Posición Horizontal en % (0-100)'),
        ),
        migrations.AlterField(
            model_name='partes_del_cuerpo',
            name='nombre',
            field=models.CharField(choices=[('cabeza', 'Cabeza'), ('cuello', 'Cuello'), ('hombro_izquierdo', 'Hombro Izquierdo'), ('hombro_derecho', 'Hombro Derecho'), ('codo_izquierdo', 'Codo Izquierdo'), ('codo_derecho', 'Codo Derecho'), ('mano_izquierda', 'Mano Izquierda'), ('mano_derecha', 'Mano Derecha'), ('pecho', 'Pecho'), ('espalda', 'Espalda'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('muslo_izquierdo', 'Muslo Izquierdo'), ('muslo_derecho', 'Muslo Derecho'), ('rodilla_izquierda', 'Rodilla Izquierda'), ('rodilla_derecha', 'Rodilla Derecha'), ('pie_izquierdo', 'Pie Izquierdo'), ('pie_derecho', 'Pie Derecho')], max_length=150),
        ),
        migrations.AlterField(
            model_name='partes_del_cuerpo',
            name='top',
            field=models.IntegerField(default=0, help_text='Posición Vertical en % (0-100)'),
        ),
    ]
