# Generated by Django 5.2.8 on 2025-12-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_alter_partes_del_cuerpo_left_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso',
            options={'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='paciente_ficticio',
            options={'verbose_name': 'Paciente Ficticio', 'verbose_name_plural': 'Pacientes Ficticios'},
        ),
        migrations.AlterModelOptions(
            name='partes_del_cuerpo',
            options={'verbose_name': 'Parte del Cuerpo', 'verbose_name_plural': 'Partes del Cuerpo'},
        ),
        migrations.AlterModelOptions(
            name='tema_interrogacion',
            options={'verbose_name': 'Tema de Interrogación', 'verbose_name_plural': 'Temas de Interrogación'},
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(choices=[('Motivo de Consulta', 'Motivo de Consulta'), ('Síntomas', 'Síntomas'), ('Examen Físico', 'Examen Físico')], max_length=50),
        ),
    ]
