# Generated by Django 5.2.8 on 2025-12-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_alter_caso_options_alter_etapa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
