# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Avance')),
                ('porcentaje_avance', models.FloatField(verbose_name='Porcentaje de avance')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=10, verbose_name='Estado')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario del estudiante')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
        ),
    ]
