# Generated by Django 5.2.8 on 2025-12-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud_inscripcion',
            options={'verbose_name': 'Solicitud de Inscripción', 'verbose_name_plural': 'Solicitudes de Inscripción'},
        ),
    ]
