# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Evaluación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nombre_estudiante', models.TextField(verbose_name='Nombre del Estudiante')),
                ('fecha_entrega', models.DateField()),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], max_length=15, verbose_name='Estado')),
                ('comentario_docente', models.TextField(blank=True, verbose_name='Comentario del Docente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.docente')),
                ('respuesta_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.respuesta_evaluacion')),
            ],
        ),
    ]
