# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Caso_Clínico', '0001_initial'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Evaluación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_evaluacion', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clínico.etapa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clínico.paciente_ficticio')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Detalle')),
                ('respuestas', models.TextField(verbose_name='Respuesta del estudiante')),
                ('retroalimentacion', models.TextField(verbose_name='Retroalimentación')),
                ('correcta', models.BooleanField(verbose_name='¿Correcta?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('puntaje_obtenido', models.FloatField(default=0, verbose_name='Puntaje')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clínico.etapa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.evaluacion')),
            ],
        ),
    ]
