# Generated by Django 5.2.8 on 2025-11-22 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_evaluacion', models.DateField()),
                ('diagnostico', models.TextField()),
                ('tiempo_total', models.DurationField()),
                ('respuestas_correctas_primer_intento', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente_ficticio')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('respuesta_estudiante', models.TextField()),
                ('retroalimentacion', models.TextField()),
                ('correcta', models.BooleanField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('puntaje_obtenido', models.FloatField(default=0)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.etapa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], max_length=15)),
                ('comentario_docente', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('respuesta_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.respuesta_evaluacion')),
            ],
        ),
    ]
