# Generated by Django 5.2.8 on 2025-12-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='en_curso', max_length=20),
        ),
    ]
