# Generated by Django 5.2.8 on 2025-12-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_evaluacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='comentario_docente',
            field=models.TextField(blank=True, help_text='Retroalimentación general del docente', null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_diagnostico',
            field=models.FloatField(blank=True, help_text='Puntaje otorgado por el docente (ej: 1 a 7)', null=True),
        ),
    ]
