# Generated by Django 5.2.8 on 2025-12-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_evaluacion_comentario_docente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='respuesta_evaluacion',
            options={'verbose_name': 'Respuesta de Evaluación', 'verbose_name_plural': 'Respuestas de Evaluaciones'},
        ),
    ]
