# Generated by Django 5.2.8 on 2025-12-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Envio_Docente',
        ),
    ]
