# Generated by Django 5.2.7 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizajeesperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Objetivo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Categoria Clinica')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Docente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del Docente')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo del Docente')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Estudiante')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del Estudiante')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo del Estudiante')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('programa', models.TextField(max_length=150, verbose_name='Programa Asignatura')),
                ('estado', models.BooleanField(verbose_name='Estado del Curso')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.aprendizajeesperado')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_Ficticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción general del Paciente')),
                ('edad', models.IntegerField(verbose_name='Edad del Paciente')),
                ('genero', models.CharField(max_length=150, verbose_name='Genero del Paciente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Etapa')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('video', models.URLField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.paciente_ficticio')),
            ],
        ),
        migrations.CreateModel(
            name='Parte_del_Cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Parte del Cuerpo:')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('imagen', models.ImageField(upload_to='')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Evaluacion')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.etapa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.paciente_ficticio')),
                ('parte_del_cuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.parte_del_cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Progreso Estudiante')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Avance Estudiante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Respuesta evaluación')),
                ('descripcion', models.TextField(verbose_name='Detalle')),
                ('retroalimentacion', models.TextField(verbose_name='Retroalimentación')),
                ('correcta', models.BooleanField(verbose_name='Correcta o incorrecta')),
                ('respuestas', models.TextField(verbose_name='Respuesta estudiante')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.etapa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la evaluación:')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nombreestudiante', models.TextField(verbose_name='Nombre estudiante:')),
                ('fechaentrega', models.DateField(verbose_name='Fecha de entrega')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente')),
                ('respuestaevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.respuesta_evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Solicitud de Inscripcion del Curso')),
                ('estado', models.BooleanField(verbose_name='Estado de la Solicitud')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Interrogacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tema')),
                ('pregunta', models.CharField(max_length=150, verbose_name='Preguntas')),
                ('respuesta', models.CharField(max_length=500, verbose_name='Respuesta')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.etapa')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tema_interrogacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tema_interrogacion'),
        ),
    ]
