# Generated by Django 5.2.8 on 2025-12-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progreso',
            options={'verbose_name': 'Progreso', 'verbose_name_plural': 'Progresos'},
        ),
    ]
