# Generated by Django 5.2.8 on 2025-12-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progreso', '0002_alter_progreso_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
